### ISSUE TITLE
close out fast travel TODO comments

### ISSUE THREAD

**Issue by ethan-moss** [datasciencecampus/transport-network-performance#182]
The following TODO comments remain outstanding in `validators.py` and `cleaners.py`, associated with fast travel:
    - [ ]  Integrate fast travel results into HTML outputs (extended outputs)
    - [ ]  Add dtype defences to `_add_validation_row()`
    - [ ]  Add datatype defences in `filter_gtfs_around_trip()`

Raised during PR #125

**Comment by r-leyshon** [comment]
Migrated to https://github.com/datasciencecampus/assess_gtfs/issues/23
